package com.gordon.rawe.business.models;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CART_ORDER".
 */
public class CartOrder {

    private Long id;
    private String commodityId;
    private Integer amount;
    private String color;
    private String size;
    private Float price;
    private String thumbnail;
    private String name;

    public CartOrder() {
    }

    public CartOrder(Long id) {
        this.id = id;
    }

    public CartOrder(Long id, String commodityId, Integer amount, String color, String size, Float price, String thumbnail, String name) {
        this.id = id;
        this.commodityId = commodityId;
        this.amount = amount;
        this.color = color;
        this.size = size;
        this.price = price;
        this.thumbnail = thumbnail;
        this.name = name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCommodityId() {
        return commodityId;
    }

    public void setCommodityId(String commodityId) {
        this.commodityId = commodityId;
    }

    public Integer getAmount() {
        return amount;
    }

    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    public String getColor() {
        return color;
    }

    public void setColor(String color) {
        this.color = color;
    }

    public String getSize() {
        return size;
    }

    public void setSize(String size) {
        this.size = size;
    }

    public Float getPrice() {
        return price;
    }

    public void setPrice(Float price) {
        this.price = price;
    }

    public String getThumbnail() {
        return thumbnail;
    }

    public void setThumbnail(String thumbnail) {
        this.thumbnail = thumbnail;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
