package com.gordon.rawe.business.models;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.gordon.rawe.business.models.DeliveryInformation;
import com.gordon.rawe.business.models.CartOrder;
import com.gordon.rawe.business.models.User;

import com.gordon.rawe.business.models.DeliveryInformationDao;
import com.gordon.rawe.business.models.CartOrderDao;
import com.gordon.rawe.business.models.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig deliveryInformationDaoConfig;
    private final DaoConfig cartOrderDaoConfig;
    private final DaoConfig userDaoConfig;

    private final DeliveryInformationDao deliveryInformationDao;
    private final CartOrderDao cartOrderDao;
    private final UserDao userDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        deliveryInformationDaoConfig = daoConfigMap.get(DeliveryInformationDao.class).clone();
        deliveryInformationDaoConfig.initIdentityScope(type);

        cartOrderDaoConfig = daoConfigMap.get(CartOrderDao.class).clone();
        cartOrderDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        deliveryInformationDao = new DeliveryInformationDao(deliveryInformationDaoConfig, this);
        cartOrderDao = new CartOrderDao(cartOrderDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(DeliveryInformation.class, deliveryInformationDao);
        registerDao(CartOrder.class, cartOrderDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        deliveryInformationDaoConfig.getIdentityScope().clear();
        cartOrderDaoConfig.getIdentityScope().clear();
        userDaoConfig.getIdentityScope().clear();
    }

    public DeliveryInformationDao getDeliveryInformationDao() {
        return deliveryInformationDao;
    }

    public CartOrderDao getCartOrderDao() {
        return cartOrderDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
