package com.gordon.rawe.business.models;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DELIVERY_INFORMATION".
 */
public class DeliveryInformation {

    private Long id;
    private String province;
    private String city;
    private String street;
    private String detail;
    private String zip;
    private String phone;

    public DeliveryInformation() {
    }

    public DeliveryInformation(Long id) {
        this.id = id;
    }

    public DeliveryInformation(Long id, String province, String city, String street, String detail, String zip, String phone) {
        this.id = id;
        this.province = province;
        this.city = city;
        this.street = street;
        this.detail = detail;
        this.zip = zip;
        this.phone = phone;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getProvince() {
        return province;
    }

    public void setProvince(String province) {
        this.province = province;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getStreet() {
        return street;
    }

    public void setStreet(String street) {
        this.street = street;
    }

    public String getDetail() {
        return detail;
    }

    public void setDetail(String detail) {
        this.detail = detail;
    }

    public String getZip() {
        return zip;
    }

    public void setZip(String zip) {
        this.zip = zip;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

}
