package com.gordon.rawe.business.models;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USER".
 */
public class User {

    private Long id;
    private String uuid;
    private String username;
    private String thumbnail;
    private String phone;
    private String address;
    private String email;
    private String gender;
    private String creditCardNumber;
    private String deliveryAddresses;

    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    public User(Long id, String uuid, String username, String thumbnail, String phone, String address, String email, String gender, String creditCardNumber, String deliveryAddresses) {
        this.id = id;
        this.uuid = uuid;
        this.username = username;
        this.thumbnail = thumbnail;
        this.phone = phone;
        this.address = address;
        this.email = email;
        this.gender = gender;
        this.creditCardNumber = creditCardNumber;
        this.deliveryAddresses = deliveryAddresses;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUuid() {
        return uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getThumbnail() {
        return thumbnail;
    }

    public void setThumbnail(String thumbnail) {
        this.thumbnail = thumbnail;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getCreditCardNumber() {
        return creditCardNumber;
    }

    public void setCreditCardNumber(String creditCardNumber) {
        this.creditCardNumber = creditCardNumber;
    }

    public String getDeliveryAddresses() {
        return deliveryAddresses;
    }

    public void setDeliveryAddresses(String deliveryAddresses) {
        this.deliveryAddresses = deliveryAddresses;
    }

}
