#!/usr/bin/python
import os
import fnmatch
os.system("rm ./src/.DS_Store")
os.system("jsonschema2pojo -s ./src -t ./java-gen -T JSON -a NONE -E -S -c")

matches = []
for root, dirnames, filenames in os.walk('./java-gen'):
    for filename in fnmatch.filter(filenames, '*.java'):
        matches.append(os.path.join(root, filename))

for file in matches:
    os.system("sed -i.bak '/Generated/d' "+file)
